// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	note "noteapp/note"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, n
func (_m *Service) Create(ctx context.Context, n *note.Note) (*note.Note, error) {
	ret := _m.Called(ctx, n)

	var r0 *note.Note
	if rf, ok := ret.Get(0).(func(context.Context, *note.Note) *note.Note); ok {
		r0 = rf(ctx, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*note.Note)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *note.Note) error); ok {
		r1 = rf(ctx, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Service) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *Service) Get(ctx context.Context, id uuid.UUID) (*note.Note, error) {
	ret := _m.Called(ctx, id)

	var r0 *note.Note
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *note.Note); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*note.Note)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, n
func (_m *Service) Update(ctx context.Context, n *note.Note) (*note.Note, error) {
	ret := _m.Called(ctx, n)

	var r0 *note.Note
	if rf, ok := ret.Get(0).(func(context.Context, *note.Note) *note.Note); ok {
		r0 = rf(ctx, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*note.Note)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *note.Note) error); ok {
		r1 = rf(ctx, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
