basePath: /v1
definitions:
  note.Note:
    properties:
      content:
        description: Content is the content of the note
        type: string
      created_time:
        description: CreatedTime is the timestamp when the note was created.
        type: string
      id:
        description: ID is a unique identifier UUID of the note.
        type: string
      is_favorite:
        description: IsFavorite is a flag when then the note is marked as favorite
        type: boolean
      title:
        description: Title is the title of the note
        type: string
      updated_time:
        description: UpdateTime is the timestamp when the note last updated.
        type: string
    type: object
  rest.CreateRequest:
    properties:
      note:
        $ref: '#/definitions/note.Note'
    type: object
  rest.CreateResponse:
    properties:
      note:
        $ref: '#/definitions/note.Note'
    type: object
  rest.ResponseError:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: jayson.vibandor@gmail.com
    name: Jayson Vibandor
  description: Noterfy Note Service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Noterfy Note Service
  version: 0.2.1
paths:
  /note:
    post:
      consumes:
      - application/json
      description: Creating a new note. The client can assign the note ID with a UUID
        value but the service will return a conflict error when the note with the
        ID provided is already exists.
      parameters:
      - description: A body containing the new note
        in: body
        name: CreateRequest
        required: true
        schema:
          $ref: '#/definitions/rest.CreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created a new note
          schema:
            $ref: '#/definitions/rest.CreateResponse'
        "409":
          description: Conflict error due to the new note with an ID already exists
            in the service
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "499":
          description: Cancel error when the request was aborted
          schema:
            $ref: '#/definitions/rest.ResponseError'
      summary: Create a new note.
  /note/{id}:
    delete:
      description: Deletes an existing note.
      parameters:
      - description: ID of the note
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: Successful deleting a note
          schema:
            type: string
        "400":
          description: Note's ID parameter is not provided in the path
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "499":
          description: Cancel error when the request was aborted
          schema:
            $ref: '#/definitions/rest.ResponseError'
      summary: Deletes an existing note.
swagger: "2.0"
